version: '3.7'

services:
  prometheus:
    image: prom/prometheus:v3.4.2  # Указанная версия (2025)
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerts.yml:/etc/prometheus/alerts.yml
    ports:
      - "9090:9090"
    restart: unless-stopped

  node-exporter:
    image: prom/node-exporter:v1.9.1  # Указанная версия (2025)
    ports:
      - "9100:9100"
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:v0.28.1  # Указанная версия (2025)
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/config.yml
    ports:
      - "9093:9093"
    command:
      - '--config.file=/etc/alertmanager/config.yml'
